apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    # Let’s Encrypt production endpoint
    server: https://acme-v02.api.letsencrypt.org/directory
    email: you@your-domain.com
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - http01:
          # use the built-in Ingress/Route solver
          ingress: {}

